In [12]:
import pandas as pd
import numpy as np

In [13]:
df = {"course":['python','ml','ml','dl','ai']}
df = pd.DataFrame(df)
df

course
0  python
1      ml
2      ml
3      dl
4      ai

In [14]:
df['course'].unique()

array(['python', 'ml', 'dl', 'ai'], dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[['course']]).toarray()

encoded # takes it in alphabetical order

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [19]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_df

course_ai  course_dl  course_ml  course_python
0        0.0        0.0        0.0            1.0
1        0.0        0.0        1.0            0.0
2        0.0        0.0        1.0            0.0
3        0.0        1.0        0.0            0.0
4        1.0        0.0        0.0            0.0

In [20]:
new_df = pd.concat([df,encoder_df],axis=1)
new_df

course  course_ai  course_dl  course_ml  course_python
0  python        0.0        0.0        0.0            1.0
1      ml        0.0        0.0        1.0            0.0
2      ml        0.0        0.0        1.0            0.0
3      dl        0.0        1.0        0.0            0.0
4      ai        1.0        0.0        0.0            0.0

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
lbl_encoder = LabelEncoder()

lbl_encoded = lbl_encoder.fit_transform(df['course'])
lbl_encoded

array([3, 2, 2, 1, 0])

In [24]:
lbl_encoder.fit_transform([['python']])


c:\Users\Ashwin V Kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0])

In [25]:
df['label_encoder'] = lbl_encoded
df

course  label_encoder
0  python              3
1      ml              2
2      ml              2
3      dl              1
4      ai              0

In [26]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
encoder = OrdinalEncoder(categories=[['python','ml','dl','ai']])

encoded = encoder.fit_transform(df[['course']])
encoded

array([[0.],
       [1.],
       [1.],
       [2.],
       [3.]])

In [32]:
df['ordinalencoder'] = encoded

In [33]:
df

course  label_encoder  ordinalencoder
0  python              3             0.0
1      ml              2             1.0
2      ml              2             1.0
3      dl              1             2.0
4      ai              0             3.0

In [34]:
df = {"course":['python','ml','ml','dl','ai'],"fee":[10000,20000,30000,40000,500000]}
df = pd.DataFrame(df)
df

course     fee
0  python   10000
1      ml   20000
2      ml   30000
3      dl   40000
4      ai  500000

In [37]:
# target encoding

mean_fee = df.groupby('course')['fee'].mean()
mean_fee

course
ai        500000.0
dl         40000.0
ml         25000.0
python     10000.0
Name: fee, dtype: float64

In [38]:
df['targetencoding'] = df['course'].map(mean_fee)
df

course     fee  targetencoding
0  python   10000         10000.0
1      ml   20000         25000.0
2      ml   30000         25000.0
3      dl   40000         40000.0
4      ai  500000        500000.0